### ISSUE TITLE
LZW31-SN Zwave-JS Config Parameter Change

### ISSUE THREAD

**Issue by drewh1991** [ryanjohnsontv/node-red-contrib-ha-inovelli-manager#43]
In zwave-js release [8.11.3](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG_v8.md#8113-2022-02-02) the config parameters changed for the LZW31-SN switch which is causing this error in node-red when setting a notification:

```
Call-service error. 1 error(s):
Node(node_id=38) - NotFoundError: Value 38-112-0-16 not found on node Node(node_id=38)
```

If I look in my zwave control panel, I now see that the values for xxx-112-0-16 are different:

![image](https://user-images.githubusercontent.com/35827438/172055427-1a00c1e1-7774-4cd1-beba-04e9c2a57b3e.png)

Here is a gist with my node-red flow: https://gist.github.com/drewh1991/98639c8a8644440da7f09ecd64818c72

**Comment by ryanjohnsontv** [comment]
I think the issue comes from attempting to use multicast without the proper setup. [Here is a write up](https://github.com/ryanjohnsontv/node-red-contrib-ha-inovelli-manager/tree/main/multicast#how-to-use) on how to configure multicast for the switches which should solve this issue. This enables a "Bulk set Param 16" parameter to cut down on bandwidth. Hopefully that's all that's needed - and thank you for bringing the changes to my attention - I need to merge those changes in to my documentation!
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/43426700/172530349-437329fe-20f4-457a-8ce7-e393c1c49105.png">

**Comment by drewh1991** [comment]
Hmm, this did not work for me. I tried rebooting and re-interviewing multiple times, but I still don't get a bulk set param for 16:

![image](https://user-images.githubusercontent.com/35827438/173101019-cbebbf62-826b-4856-b0e4-1a0008cc9d8b.png)

All of my switches are firmware v. 1.57

**Comment by ryanjohnsontv** [comment]
It can be a bit hard to catch in the logs, but when ZWaveJS boots up are you able to see any error regarding loading the custom configuration from the store directory? I had this issue with the recent config update and turns out I wasn't including the master_template.json file which is now referenced for the LZW31-SN config. If there is another issue at play it should be logged as to why it's defaulting to the included config as opposed to the custom one.

**Comment by drewh1991** [comment]
I finally got it to show up after re-adding the json files to the config folder. Maybe I mis-copy/pasted something. That resolved the issue, thanks for your help! And thanks for creating these awesome nodes!
